[CmdletBinding()]
param(
    [switch]$Check
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$workspace = [System.IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..'))
$sourcePath = Join-Path $workspace 'src\shared\CodexControl.Protocol\RelayMessageTypes.cs'
$targetPath = Join-Path $workspace 'src\web\src\messageTypes.generated.ts'
$pattern = '^\s*public const string (?<name>[A-Za-z][A-Za-z0-9]*) = "(?<value>[^"]+)";\s*$'

$entries = foreach ($line in [System.IO.File]::ReadAllLines($sourcePath)) {
    $match = [System.Text.RegularExpressions.Regex]::Match($line, $pattern)
    if ($match.Success) {
        $name = $match.Groups['name'].Value
        [pscustomobject]@{
            Name = $name.Substring(0, 1).ToLowerInvariant() + $name.Substring(1)
            Value = $match.Groups['value'].Value
        }
    }
}

if ($entries.Count -eq 0) {
    throw "No protocol message types found in $sourcePath"
}

$lines = [System.Collections.Generic.List[string]]::new()
$lines.Add('// <auto-generated />')
$lines.Add('// Source: src/shared/CodexControl.Protocol/RelayMessageTypes.cs')
$lines.Add('// Run tools/Sync-ProtocolMessageTypes.ps1 after changing the C# constants.')
$lines.Add('export const MessageType = {')
foreach ($entry in $entries) {
    $lines.Add("  $($entry.Name): '$($entry.Value)',")
}
$lines.Add('} as const;')
$lines.Add('')
$expected = [string]::Join("`n", $lines)

if ($Check) {
    if (-not (Test-Path -LiteralPath $targetPath)) {
        throw "Generated protocol file is missing: $targetPath"
    }

    $actual = [System.IO.File]::ReadAllText($targetPath).Replace("`r`n", "`n")
    if ($actual -ne $expected) {
        throw 'Generated Web protocol message types are stale. Run tools/Sync-ProtocolMessageTypes.ps1.'
    }

    Write-Output 'Protocol message types are synchronized.'
    return
}

[System.IO.File]::WriteAllText(
    $targetPath,
    $expected,
    [System.Text.UTF8Encoding]::new($false))
Write-Output "Generated: $targetPath"
